### ISSUE TITLE
About training my style

### ISSUE THREAD

**Issue by sunmin-lee99** [zideliu/StyleDrop-PyTorch#12]
Thank you for your great work.

I want to train my own image to generate style.
But I feel like the result images are just well generated in certain prompts which are in custom_dataset.py.(ex. A banana on the table)
How can I train my own prompts in styledrop model?

**Comment by zideliu** [comment]
If you mean sampling results during training, you can edit [test_custom_dataset](https://github.com/zideliu/StyleDrop-PyTorch/blob/a8d8449f78403e6820acc67392ded13e2696ea3c/custom/custom_dataset.py#L21) and [Discriptor](https://github.com/zideliu/StyleDrop-PyTorch/blob/a8d8449f78403e6820acc67392ded13e2696ea3c/custom/custom_dataset.py#L128)

> How can I train my own prompts in styledrop model?

Modify [`one_style.json`](https://github.com/zideliu/StyleDrop-PyTorch/blob/a8d8449f78403e6820acc67392ded13e2696ea3c/data/one_style.json#L2) for your style image

**Comment by zideliu** [comment]
In order to see the training situation well, I fixed the prompt used for sampling during the training process,[here](https://github.com/zideliu/StyleDrop-PyTorch/blob/a8d8449f78403e6820acc67392ded13e2696ea3c/train_t2i_custom_v2.py#L292)

**Comment by sunmin-lee99** [comment]
Thank you for answering!🙇‍♂️
