### ISSUE TITLE
How to get the prompts?

### ISSUE THREAD

**Issue by syguan96** [zideliu/StyleDrop-PyTorch#14]
Hi @zideliu , congratulations on your excellent work. I want to try it in my data. Could you please share how to obtain the captions in your format?

**Comment by zideliu** [comment]
If you mean how to construct prompts, just follow [here](https://github.com/zideliu/StyleDrop-PyTorch#train), and `data/data.json` can be used for your reference

<img width="1003" alt="image" src="https://github.com/zideliu/StyleDrop-PyTorch/assets/34944964/1ed88a91-2a0e-4412-9688-4564ba42ad8e">

**Comment by syguan96** [comment]
Thank you, so all prompts are manually annotated?

**Comment by zideliu** [comment]
yes

**Comment by syguan96** [comment]
I see! Thanks for your reply!
