### ISSUE TITLE
Issues runnin 

### ISSUE THREAD

**Issue by thoughtformer** [zideliu/StyleDrop-PyTorch#15]
Hi there

When I try to run inside the StyleDrop-Pytorch folder
```python
python extract_empty_feature.py
``` 

I receive the following error:
```python
ModuleNotFoundError: No module named 'torch'
``` 

My Python knowledge is very limited so forgive me if I ask any stupid questions.

**Comment by zideliu** [comment]
This error indicates that you do not have the appropriate python package installed, please install [Dependencies](https://github.com/zideliu/StyleDrop-PyTorch#dependencies) first
