### ISSUE TITLE
the path and effect issues of style_adapter

### ISSUE THREAD

**Issue by chenkai-666** [zideliu/StyleDrop-PyTorch#19]
hi,
I followed the instructions to place the weight of style_adapter under the path of style_adapter
![image](https://github.com/zideliu/StyleDrop-PyTorch/assets/81290054/120ffd1d-04e4-495e-890f-63a293bd087e)
but the corresponding weight name is not displayed on the gradio page
![image](https://github.com/zideliu/StyleDrop-PyTorch/assets/81290054/11cac176-aa6e-4fd9-a62b-c82e9dfb6f81)
Then I changed the folder structure and placed corresponding weights in each folder, naming it adapter.pth
![image](https://github.com/zideliu/StyleDrop-PyTorch/assets/81290054/2996148d-9d92-4ef8-8fe7-4052aad99da7)
![image](https://github.com/zideliu/StyleDrop-PyTorch/assets/81290054/a47c2662-87af-4f9f-b319-04d893d114f9)
![image](https://github.com/zideliu/StyleDrop-PyTorch/assets/81290054/2ab17262-f765-455c-82d6-b7eed916c14b)
At this point, I read about the model weights, but the effect is completely different, as if it doesn't work at all.
![image](https://github.com/zideliu/StyleDrop-PyTorch/assets/81290054/f94b17af-d1b1-48cb-a486-a831a92ee350)
How can I fix this problem……

**Comment by zideliu** [comment]
Sorry, is my fault, just edit `style_postfix` in [here](https://github.com/zideliu/StyleDrop-PyTorch/blob/a8d8449f78403e6820acc67392ded13e2696ea3c/gradio_demo.py#L130)
```python
style_postfix ={
    "None":"",
    "0102":" in watercolor painting style",
    "0103":" in watercolor painting style",
    "0106":" in line drawing style",
    "0108":" in oil painting style",
    "0301":" in 3d rendering style",
    "0305":" in kid crayon drawing style",
}
```
<img width="280" alt="image" src="https://github.com/zideliu/StyleDrop-PyTorch/assets/34944964/60ca0e6d-26fd-4816-99b3-2e8d41279f43">

**Comment by chenkai-666** [comment]
Thanks. It works!
