### ISSUE TITLE
I made a colab demo but i get 2 erros

### ISSUE THREAD

**Issue by francqz31** [zideliu/StyleDrop-PyTorch#2]
Hi Authors ,
Here is a  full demo Colab that you can build on , but I get these 2 errors

https://colab.research.google.com/drive/13BIlDBZK4rcrzLxK3N7tamrPcvX6lAIB#scrollTo=HcBUTwmFjpUT

whenever i run the inference or the training scripts I get this error 
subprocess.CalledProcessError: Command '['/usr/local/bin/python3.10', 'train_t2i_custom_v2.py', '--config=configs/custom.py']' died with <Signals.SIGKILL: 9>.

and whenever i run this !python gradio_demo.py i get this error
2023-07-04 15:37:43.188 | DEBUG    | open_clip.transformer:__init__:314 - xattn in transformer of CLIP is False
2023-07-04 15:38:02.273 | DEBUG    | open_clip.transformer:__init__:314 - xattn in transformer of CLIP is False
^C
I'm not sure what's happening but if you can identify the problem that would be amazing.
Thanks in advance

**Comment by loboere** [comment]
could you fix this?

**Comment by loboere** [comment]
the first time i run
!python gradio_demo.py
it seems to download a 10.2gb file

Downloading (…)ip_pytorch_model.bin: 94% 9.56G/10.2G [09:16<00:22, 26.9MB/s

then I guess it tries to load into memory but with the memory that colab gives free it is not enough so it gives that error.
It would be a shame if this is it.

You would have to try colab pro if you have colab pro you can try it.

**Comment by chenxwh** [comment]
did you try the gradio demo? I am getting random output

**Comment by zideliu** [comment]
The gradio demo is now deployed to HuggingFace space, available [here](https://huggingface.co/spaces/zideliu/styledrop).
Unlike [gradio_demo](https://github.com/zideliu/StyleDrop-PyTorch/blob/10eb5e0fb55f5fc147a645670af75ee410fc3de3/gradio_demo.py#L100) in this repo, we use`prompt_model,_,_ = open_clip.create_model_and_transforms('ViT-bigG-14', 'laion2b_s39b_b160k',device='cpu')` which use 'fp16' as default

**Comment by ship-it-mind** [comment]
@loboere @francqz31 I faced the same error on colab the free version but after upgrading to the pro version it worked. So the issue happens because of not enough RAM or VRAM
