### ISSUE TITLE
About training data;关于训练数据。

### ISSUE THREAD

**Issue by LiuHuijie6410** [zideliu/StyleDrop-PyTorch#25]
Congratulations on such a beautiful job, But I encountered some problems while running this project, could you please answer me？
1. How should I obtain the dataset mentioned in the StyleDrop paper?
2. For one specific style, approximately how many pictures need to be used for fine-tuning?

**Comment by zideliu** [comment]
1. I got the data from the StyleDrop paper [paper source file](https://arxiv.org/e-print/2306.00983)
2. According to the paper, one is enough.
