### ISSUE TITLE
关于模型请教

### ISSUE THREAD

**Issue by ltm920716** [zideliu/StyleDrop-PyTorch#4]
你好，
关于工程里的vqvan权重，与muse的权重，请教一下这两个是训练时匹配的么，我想了解的是，如果这个muse的权重不是基于这个vqgan权重基础上训练得出来的，那对encode-token的重构影响大不大，谢谢

**Comment by zideliu** [comment]
是匹配的，[here](https://github.com/zideliu/StyleDrop-PyTorch/blob/fc5d4d1d56b093813cac19ee170254ecf4fb8c3f/libs/uvit_t2i_vq.py#L200)，你说的应该是这个意思？
> 我想了解的是，如果这个muse的权重不是基于这个vqgan权重基础上训练得出来的，那对encode-token的重构影响大不大

这个我没有做实验，你可以尝试一下
